name: first workflow
on: push
jobs:
  my-job:
    runs-on: ubuntu-lastest
    steps:
      - name: checkout code
        uses:  actions/checkout@v4
      - name: Read-File
        run: cat hello.txt

  